NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, login_form
from django.contrib.auth import views as auth_views
from .views import IndexView, ProfileView, ProfileUpdate


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('News_Portal.urls')),
    path('articles/', include('News_Portal.urls')),
    path('posts/', include('News_Portal.urls')),
    path('', IndexView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('profile/edit/', ProfileUpdate.as_view()),
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

NewsPortal/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import upgrade_me

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='login_form.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name='logout.html'),
         name='logout'),
    path('upgrade/', upgrade_me, name='upgrade')
]

NewsPortal/News_Portal/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.user.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        postcommentRat = self.post_set.comment_set.aggregate(postcommentRating=Sum('rating'))
        pcRat = 0
        pcRat += postcommentRat.get('postcommentRating')

        self.rating = pRat * 3 + cRat + pcRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(to=User, related_name='subscriptions')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор')

    ARTICLE = 'AR'
    NEWS = 'NW'

    TYPES = [
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    ]

    post_type = models.CharField(max_length=2,
                                 choices=TYPES,
                                 default=ARTICLE)

    publication_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    categories = models.ManyToManyField('Category', through='PostCategory', verbose_name='Категория')
    heading = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def get_absolute_url(self):
        return f'/posts/{self.pk}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...'


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPortal/templates/base.html
{% extends 'flatpages/default.html' %}

<head>
    <title>{% block head_title %}Регистрация{% endblock head_title %}</title>
</head>
<body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
</body>

NewsPortal/templates/categorylist.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <h1>Все категории</h1>

    {% if categorylist %}
        <ul>
        {% for cat in categorylist %}
        <li>
            {{ cat.name }}
            <!---<input type="submit" value="Подписаться"></form>---!>
            <a href="/posts/categories/{{ cat.pk }}/subscribe">Подписаться</a>
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">В начало</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">В конец</a>
        {% endif %}

    {% endif %}

{% endblock content %}

NewsPortal/templates/create_post_form.html
{% extends 'flatpages/default.html' %}

{% block title %}
Create post
{% endblock title %}

{% block content %}
<br>
<form method="POST">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit"/>
</form>
{% endblock content %}

NewsPortal/templates/delete_post_form.html
{% extends 'flatpages/default.html' %}
 
{% block title %} Posts list {% endblock title %}
 
{% block content %}
<h1>{{ posts.heading }}</h1>
<p>{{ posts.publication_time | date:"H-M-Y" }} {{ posts.publication_time | time:"H:i" }}</p>
<p>{{ posts.author.user.username }}</p>
{% for category in posts.categories.all %}
{{ category.name }}
{% endfor %}
<p></p>
<p>{{ posts.text }}</p>
<h2>Вы действительно хотите удалить данную запись?</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Да"></form>
    <a href="/posts/">Нет</a>
{% endblock content %} 

NewsPortal/templates/edit_profile_form.html
{% extends 'flatpages/default.html' %}

{% block title %}
Редактировать профиль
{% endblock title %}

{% block content %}
<br>
<form method="POST">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit"/>
</form>
{% endblock content %}

NewsPortal/templates/index.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Бобрам пожаловаться! </h1>
{% endblock %}

NewsPortal/templates/login_form.html
{% extends 'flatpages/default.html' %}

{% block content %}

{% if form.errors %}
<p>Неверный логин или пароль. Попробуйте ещё раз.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Недостаточно прав доступа.</p>
    {% else %}
    <p>Доступ только для зарегистрированных пользователей.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<h2> Войти в систему </h2>
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

NewsPortal/templates/logout.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

NewsPortal/templates/newslist.html
{% extends 'flatpages/default.html' %}

{% block title %}
All news
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>

    <p><a href="/news/add">Добавить новость</a></p>
    <p><a href="/news/search">Поиск</a></p>

    {% if newslist %}
        <ul>
        {% for post in newslist %}
        <li>
          <a href="/news/{{ post.pk }}">{{ post.heading }}</a>
            <p>{{ post.publication_time | date:"d-M-Y" }} {{ post.publication_time | time:"H:i" }}</p>
            <p>{{ post.text|truncatechars:50 }}</p>
            <p>{{ post.author.user.username }}</p>
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">В начало</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">В конец</a>
        {% endif %}

    {% endif %}

{% endblock content %}

NewsPortal/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
{{ posts.heading | censor }}
{% endblock title %}

{% block content %}
<h1>{{ posts.heading | censor }}</h1>
<p>{{ posts.publication_time | date:"d-M-Y" }} {{ posts.publication_time | time:"H:i" }}</p>
<p>{{ posts.author.user.username }}</p>
{% for category in posts.categories.all %}
#{{ category.name }}
{% endfor %}
<p>
    <a href="/posts/categories/">Смотреть все категории</a>
</p>
<p></p>
<p>{{ posts.text | censor }}</p>

<p><a href="/posts/{{ posts.pk }}/edit">Редактировать</a></p>
<p><a href="/posts/{{ posts.pk }}/delete">Удалить</a></p>
{% endblock content %}

NewsPortal/templates/postslist.html
{% extends 'flatpages/default.html' %}

{% block title %}
All posts
{% endblock title %}

{% block content %}
    <h1>Все публикации</h1>

    <p><a href="/posts/add">Добавить публикацию</a></p>
    <p><a href="/posts/search">Поиск</a></p>

    {% if postslist %}
        <ul>
        {% for post in postslist %}
        <li>
          <a href="/posts/{{ post.pk }}">{{ post.heading }}</a>
            <p>{{ post.publication_time | date:"d-M-Y" }} {{ post.publication_time | time:"H:i" }}</p>
            <p>{{ post.text|truncatechars:50 }}</p>
            <p>{{ post.author.user.username }}</p>
            <p>{{ post.post_type }}</p>
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <h2>Ничего нет!</h2>
    {% endif %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">В начало</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">В конец</a>
        {% endif %}

    {% endif %}

{% endblock content %}

NewsPortal/templates/profile.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<p>{{ request.user.first_name }}</p>
<p>{{ request.user.last_name }}</p>
<p>{{ request.user.email }}</p>

<h3>Подписки</h3>
{% for cat in request.user.category_set.all %}
<p>{{ cat.name }}</p>
{% endfor %}


<p><a href="/profile/edit/">Редактировать профиль</a></p>
<!-- <p><a href="/news/{{ news.pk }}/delete">Удалить профиль</a></p> -->

{% if is_not_authors %}
<button> <a href="/sign/upgrade/"> Стать автором </a> </button>
{% endif %}

<button> <a href="/sign/logout/">Выйти</a> </button>
{% endblock %}

NewsPortal/templates/search.html
{% extends 'flatpages/default.html' %}

{% block title %}
Search
{% endblock title %}

{% block content %}
    <br>
    <form method="GET" action="/posts/">
    {{ filter.form.as_p }}
    <input name="date_search" type="date" value="{{ date_search }}"/>
    <input type="submit" value="Найти">
    </form>

{% endblock content %}